### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Xen1290** [hilburn/HardcoreFixes#1]
Hi @hilburn, I get this crash when I try to enter in game, I think is an incompatibility with Galacticraft:
HQM Version: 4.2.2
HardcoreFixes:0.1.1
Galacticraft: 1.7-3.0.11.309

http://pastebin.com/60eVykv8

**Comment by hilburn** [comment]
fricking galacticraft...

**Comment by hilburn** [comment]
Should be fixed - try 0.1.2

**Comment by Xen1290** [comment]
Thanks, I'll try it!

**Comment by Xen1290** [comment]
Fixed, thank you @hilburn !
